logging:
  level:
    course.configuration.logging: DEBUG
    course.error: ERROR
  file.name: error.log
  file.path: logs

spring:
  datasource:
    url: jdbc:h2:mem:course
    platform: h2
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
